# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

snapcrafts:
  -
    # The name of the snap. This is optional.
    # Default is project name.
    name: bare-cli 
    publish: true
    summary: Create projects from boilerplate faster than ever
    description: This is the best drum roll application out there. Install it and awe!

    grade: devel 

    confinement: strict

    license: MIT

    layout:
      /etc/bare-cli:
        bind: $SNAP_DATA/etc 

    apps:
        bare-cli:
            command: bare
