name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bare-cli'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Setup
      run: make setup
      
    - name: Go format
      run: diff -u <(echo -n) <(gofmt -d ./)
    
    - name: Build
      run: make build
